version: '1.0'

services:
  app:
    image: task_scheduler
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    command: uvicorn --port 80 --host 0.0.0.0 --lifespan on --reload main:app --reload-dir /app
    volumes:
      - ./src:/app
    restart: always
