version: '1.0'

services:
  app:
    image: task_scheduler
    container_name: task_scheduler_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    command: uvicorn --port 80 --host 0.0.0.0 --lifespan on --reload main:app --reload-dir /app
    volumes:
      - ./src:/app
    restart: always
    depends_on:
      - db
      - redis

  db:
    image: postgres:16-alpine
    container_name: db_app
    env_file:
      - .env-non-dev

  redis:
    image: redis:7-alpine
    container_name: redis_app
    env_file:
      - .env-non-dev
