version: "1"

services:

  app:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./src:/app
    ports:
      - "8080:80"
    command: /venv/bin/uvicorn --port 8080 --host 0.0.0.0 --lifespan on --reload main:app
